services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: smartcfd-agent
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    environment:
      # Pass Alpaca credentials directly from the .env file
      APCA_API_KEY_ID: ${APCA_API_KEY_ID}
      APCA_API_SECRET_KEY: ${APCA_API_SECRET_KEY}
      
      # Safe defaults if .env variables are missing
      TIMEZONE: ${TIMEZONE:-America/New_York}
      ALPACA_ENV: ${ALPACA_ENV:-paper}
      API_TIMEOUT_SECONDS: ${API_TIMEOUT_SECONDS:-10}
      NETWORK_MAX_BACKOFF_SECONDS: ${NETWORK_MAX_BACKOFF_SECONDS:-60}
      ON_RECONNECT_RECONCILE: ${ON_RECONNECT_RECONCILE:-true}
      RUN_CONTAINER_SMOKE_TEST: ${RUN_CONTAINER_SMOKE_TEST:-1}
    healthcheck:
      test: ["CMD", "python", "/app/docker/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s