services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: smartcfd-agent
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./configs:/app/configs:ro
      - ./config.ini:/app/config.ini:ro
      - ./models:/app/models:ro
      - ./logs:/app/logs
      - ./reports:/app/reports
    environment:
      # Environment variables are now secondary to config.ini
      TIMEZONE: ${TIMEZONE:-America/New_York}
      ALPACA_ENV: ${ALPACA_ENV:-paper}
      API_TIMEOUT_SECONDS: ${API_TIMEOUT_SECONDS:-10}
      NETWORK_MAX_BACKOFF_SECONDS: ${NETWORK_MAX_BACKOFF_SECONDS:-60}
      ON_RECONNECT_RECONCILE: ${ON_RECONNECT_RECONCILE:-true}
      RUN_CONTAINER_SMOKE_TEST: ${RUN_CONTAINER_SMOKE_TEST:-1}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "python", "/app/docker/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  retrain:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: smartcfd-retrain
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ./configs:/app/configs:ro
      - ./config.ini:/app/config.ini:ro
      - ./models:/app/models
      - ./reports:/app/reports
    command: ["python", "scripts/retrain_model.py"]
    env_file:
      - .env
