profiles:
  crypto_1h:
    watch: [BTC-USD, ETH-USD]
    interval: "1h"
    intervals: "15m,1h"
    interval_weights: "15m=1,1h=2"
    vote: true
    adx: 10
    ema_fast: 10
    ema_slow: 20
    macd_signal: 5
    risk: 0.02
    equity: 1000
    cooldown_min: 30
    class_caps:
      crypto: 2
    class_risk_budget:
      crypto: 0.10
    max_trades: 10
    grace: 0
