profiles:
  crypto_1h:
    watch: [BTC-USD, ETH-USD, SOL-USD, ADA-USD, LTC-USD, BCH-USD, DOGE-USD, XRP-USD, LINK-USD, MATIC-USD, DOT-USD, AVAX-USD]
    interval: "1h"
    intervals: "15m,1h"
    interval_weights: "15m=1,1h=2"
    vote: true
    use_params: true
    ml_model: SmartCFDTradingAgent/storage/ml_model.pkl
    ml_threshold: 0.65
    ml_blend: auto
    budget_mode: auto
    retrain_on_dry_run: true
    retrain_interval_hours: 4
    adx: 10
    ema_fast: 10
    ema_slow: 20
    macd_signal: 5
    risk: 0.02
    max_total_exposure_percent: 50.0
    max_exposure_per_asset_percent: 25.0
    equity: 1000
    cooldown_min: 30
    class_caps:
      crypto: 2
    max_trades: 10
    grace: 0
    # --- Circuit Breaker Settings ---
    # Halt trading if the current true range exceeds ATR by this multiplier.
    # A value of 0 disables the circuit breaker.
    circuit_breaker_atr_multiplier: 3.5
