profiles:
  equities_daily:
    watch:
      - SPY
      - QQQ
      - DIA
      - IWM
    interval: "1d"
    use_params: true
    ml_model: SmartCFDTradingAgent/storage/ml_model.pkl
    ml_threshold: 0.65
    ml_blend: auto
    budget_mode: auto
    retrain_on_dry_run: true
    retrain_interval_hours: 4
    interval_weights: ""
    adx: 8
    ema_fast: 15
    ema_slow: 30
    macd_signal: 7
    risk: 0.01
    max_total_exposure_percent: 40.0
    max_exposure_per_asset_percent: 20.0
    equity: 1000
    cooldown_min: 60
    class_caps:
      equity: 2
    max_trades: 2
    grace: 120
