name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-lint-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy
      - name: Lint with ruff
        run: |
          ruff check .
      - name: Type check with mypy
        run: |
          mypy . --exclude venv --exclude .venv --ignore-missing-imports
      - name: Run all tests
        run: |
          pytest -q tests/ --maxfail=2 --disable-warnings
