name: CI

on:
  pull_request:
  push:
    branches: [ main, refactor/** ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pytest only (quick and reliable for smoke test)
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run only the smoke test for now
        run: |
          pytest -q tests/test_smoke.py --maxfail=1 --disable-warnings
