name: Build and publish Docker image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image name (lowercase owner)
        run: |
          OWNER_LC="$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"
          IMAGE="ghcr.io/${OWNER_LC}/smartcfdtradingagent:sha-${{ github.sha }}"
          echo "IMAGE=$IMAGE" >> "$GITHUB_ENV"

      - name: Build image
        run: |
          docker build -f docker/Dockerfile -t "$IMAGE" .

      - name: Push image
        run: docker push "$IMAGE"
